### ISSUE TITLE
Melhorar output do programa

### ISSUE THREAD

**Issue by angelo-daumas** [RenanMALV/simulacao-de-escalonamento-de-processos#16]

**Comment by RenanMALV** [comment]
## Implementado:
- Output das filas de pronto 
- Função com parâmetros necessários para printar os processos novos
- Função com parâmetros necessários para printar os processos em execução
## Falta implementar:
- Output das filas de I/O
- Declarar a função em cretor,h
- criar um queue_copy para conseguir printar as filas de cada arquivo sem ter que aumentar o escopo  delas e aumentar o acoplamento da codebase
- criar um queue_print para facilitar a vida
